"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { ChangeEvent } from "react";
import {
  DEG, adaptiveAnalyze, add, analysisToCsv, dynamicsBreakdown, kinematics, magnitude,
  mechanismClass, mul, sampleAngleRange, solvePose, summarizeAnalysis, wrapDegrees,
} from "../lib/linkage-analysis.mjs";
import type { DynamicsBreakdown } from "../lib/linkage-analysis.mjs";
import { validateConfig } from "../lib/input-validation.mjs";
import { DEFAULT_CONFIG, NumericInput, Plot, RailLimit, fieldGroups, peakMeta, safetyText } from "./linkage-ui";
import type { Config, Vec } from "./linkage-ui";

export default function Home() {
  const [config, setConfig] = useState<Config>(DEFAULT_CONFIG);
  const [playing, setPlaying] = useState(false);
  const lastFrame = useRef<number | null>(null); const direction = useRef<1|-1>(1);
  const update = <K extends keyof Config>(key: K, value: Config[K]) => setConfig((c) => ({ ...c, [key]: value }));

  useEffect(() => { if (!playing) { lastFrame.current=null; return; } let frame=0; const tick=(t:number)=>{ if(lastFrame.current!==null) setConfig((c)=>{ const dt=Math.min(.05,(t-lastFrame.current!)/1000), span=c.maxAngle-c.minAngle; if(span>=359.5) return {...c,angle:wrapDegrees(c.angle+c.rpm*6*dt)}; let next=c.angle+direction.current*Math.abs(c.rpm)*6*dt; if(next>=c.maxAngle){next=c.maxAngle;direction.current=-1;} if(next<=c.minAngle){next=c.minAngle;direction.current=1;} return {...c,angle:next}; }); lastFrame.current=t; frame=requestAnimationFrame(tick); }; frame=requestAnimationFrame(tick); return()=>cancelAnimationFrame(frame); },[playing]);

  const errors=useMemo(()=>validateConfig(config),[config]); const valid=Object.keys(errors).length===0;
  const pose=useMemo(()=>solvePose(config),[config]); const kin=useMemo(()=>kinematics(config,pose),[config,pose]); const cls=useMemo(()=>mechanismClass(config),[config]);
  const current=useMemo<DynamicsBreakdown>(()=>valid?dynamicsBreakdown(config):{total:null,external:null,gravity:null,inertia:null},[config,valid]);
  const adaptive=useMemo(()=>valid?adaptiveAnalyze(config,{coarseStepDeg:10,angleToleranceDeg:.05,maxDepth:12}):null,[config,valid]);
  const summary=useMemo(()=>adaptive?summarizeAnalysis(config,adaptive,current):null,[config,adaptive,current]); const samples=adaptive?.samples??[];
  const geometry=useMemo(()=>sampleAngleRange(0,360,2).map((angle)=>({angle,pose:solvePose(config,angle)})),[config.groundX,config.groundY,config.crank,config.coupler,config.rocker,config.toolAlong,config.toolOffset,config.branch]);
  const reachable=geometry.filter((s)=>s.pose); const coverage=reachable.length/geometry.length;
  const points:Vec[]=[{x:0,y:0},{x:config.groundX,y:config.groundY},...reachable.flatMap((s)=>s.pose?[s.pose.A,s.pose.B,s.pose.T]:[])]; const xs=points.map(p=>p.x),ys=points.map(p=>p.y); const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys); const W=900,H=580,pad=60,scale=Math.min((W-2*pad)/Math.max(50,maxX-minX),(H-2*pad)/Math.max(50,maxY-minY)); const cx=(minX+maxX)/2,cy=(minY+maxY)/2; const map=(p:Vec)=>({x:W/2+(p.x-cx)*scale,y:H/2-(p.y-cy)*scale});
  const path=geometry.reduce((d,s)=>{if(!s.pose)return d+" M";const p=map(s.pose.T);return d+`${d.endsWith("M")||!d?"M":"L"}${p.x.toFixed(1)},${p.y.toFixed(1)} `;},"").replace(/ M M/g," M"); const mp=pose?{O2:map(pose.O2),O4:map(pose.O4),A:map(pose.A),B:map(pose.B),T:map(pose.T)}:null;
  const fmag=Math.hypot(config.forceX,config.forceY); const fend=pose&&fmag>1e-9?map(add(pose.T,mul({x:config.forceX,y:config.forceY},36/fmag))):null;
  const setMin=(v:number)=>setConfig(c=>({...c,minAngle:v,angle:c.angle<v?v:c.angle})); const setMax=(v:number)=>setConfig(c=>({...c,maxAngle:v,angle:c.angle>v?v:c.angle}));
  const exportCsv=()=>{if(!adaptive)return;const url=URL.createObjectURL(new Blob([analysisToCsv(adaptive)],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="robot-leg-linkage-analysis.csv";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const reactions=current.total?[["O₂ ground → crank",current.total.O2Reaction],["A coupler → crank",current.total.AReaction],["B rocker → coupler",current.total.BReaction],["O₄ ground → rocker",current.total.O4Reaction]] as Array<[string,Vec]>:[];

  return <main className="site-shell">
    <header className="topbar"><div className="brand-lockup"><p className="eyebrow">Planar mechanism workbench</p><h1>Robot Leg Linkage Lab</h1></div><div className="header-status"><span className={`status-dot ${!pose?"danger":pose.transmission<35?"warning":"good"}`}/><span>{pose?"Assembly solved":"Unreachable pose"}</span><span className="separator">/</span><span>{cls.type}</span></div></header>
    <nav className="mobile-jump"><a href="#simulator">Model</a><a href="#inputs">Inputs</a><a href="#results">Results</a></nav>
    <div className="workspace">
      <aside id="inputs" className="control-panel"><div className="panel-heading"><div><span className="panel-index">01</span><div><h2>Inputs</h2><p>Draft → validate → commit</p></div></div><button className="text-button" type="button" onClick={()=>{setConfig(DEFAULT_CONFIG);setPlaying(false);}}>Reset preset</button></div>
        {fieldGroups(config).map((g)=><section className="control-section" key={g.title}><div className="section-label"><h3>{g.title}</h3><span>{g.note}</span></div><div className="field-grid">{g.fields.map((f)=><NumericInput key={f.key} label={f.label} unit={f.unit} step={f.step} min={f.min} max={f.max} integer={f.integer} validate={f.validate} value={config[f.key]} onCommit={(v)=>update(f.key,v)}/>)}</div></section>)}
        <section className="control-section compact-section"><div className="section-label"><h3>Assembly & gravity</h3><span>discrete settings</span></div><label className="field"><span>Assembly branch</span><span className="input-wrap select-wrap"><select value={config.branch} onChange={(e:ChangeEvent<HTMLSelectElement>)=>update("branch",Number(e.target.value) as Config["branch"])}><option value={-1}>Lower / drawing</option><option value={1}>Upper / alternate</option></select></span></label><label className="toggle-field"><span>Gravity −y</span><input type="checkbox" checked={config.gravity} onChange={(e:ChangeEvent<HTMLInputElement>)=>update("gravity",e.target.checked)}/></label></section>
        <section className="mechanism-summary"><div><span>Ground length</span><strong>{cls.ground.toFixed(2)} mm</strong></div><div><span>Grashof margin</span><strong className={cls.margin<0?"value-danger":""}>{cls.margin.toFixed(2)} mm</strong></div><div><span>Full rotation</span><strong>{cls.inputRotates&&coverage>.99?"Yes":"No"}</strong></div><div><span>Reachable cycle</span><strong>{(coverage*100).toFixed(0)}%</strong></div></section>
      </aside>
      <section id="simulator" className="analysis-area"><article className="simulator-card"><div className="card-heading"><div><span className="panel-index">02</span><div><h2>Kinematic preview</h2><p>Preview motion only · endpoint reversals excluded from dynamics</p></div></div></div><div className="simulator-body"><div className="simulator-stage"><svg viewBox={`0 0 ${W} ${H}`} role="img" aria-label="Robot leg four-bar linkage"><defs><pattern id="grid" width="32" height="32" patternUnits="userSpaceOnUse"><path d="M32 0H0V32" className="grid-line"/></pattern><marker id="force-arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" className="force-arrow-head"/></marker></defs><rect width="100%" height="100%" fill="url(#grid)"/><path d={path} className="tool-path"/>{mp&&pose?<><line x1={mp.O2.x} y1={mp.O2.y} x2={mp.O4.x} y2={mp.O4.y} className="ground-link"/><line x1={mp.O2.x} y1={mp.O2.y} x2={mp.A.x} y2={mp.A.y} className="link crank-link"/><line x1={mp.A.x} y1={mp.A.y} x2={mp.T.x} y2={mp.T.y} className="link coupler-link"/><line x1={mp.O4.x} y1={mp.O4.y} x2={mp.B.x} y2={mp.B.y} className="link rocker-link"/>{[[mp.O2,"fixed-joint"],[mp.O4,"fixed-joint"],[mp.A,"moving-joint"],[mp.B,"moving-joint"],[mp.T,"tool-joint"]].map(([p,c],i)=><circle key={i} cx={(p as Vec).x} cy={(p as Vec).y} r={i===4?10:8} className={c as string}/>)}{fend?<g className="force-vector"><line x1={mp.T.x} y1={mp.T.y} x2={fend.x} y2={fend.y} markerEnd="url(#force-arrow)"/><text x={fend.x+10} y={fend.y-8}>{fmag.toFixed(0)} N</text></g>:null}</>:null}</svg><div className="stage-coordinate">θ₂ {config.angle.toFixed(1)}°</div></div><div className="motion-rail"><div className="rail-readout"><span>θ₂</span><output>{config.angle.toFixed(1)}°</output></div><div className="rail-range"><RailLimit label="Max" value={config.maxAngle} min={config.minAngle+.5} max={360} onCommit={setMax}/><input id="crank-angle" className="vertical-angle-slider" type="range" min={config.minAngle} max={config.maxAngle} step="0.5" value={config.angle} onChange={(e:ChangeEvent<HTMLInputElement>)=>{setPlaying(false);update("angle",Number(e.target.value));}}/><RailLimit label="Min" value={config.minAngle} min={0} max={config.maxAngle-.5} onCommit={setMin}/></div><div className="rail-nudges"><button type="button" onClick={()=>{setPlaying(false);update("angle",Math.max(config.minAngle,config.angle-5));}}>−5°</button><button type="button" onClick={()=>{setPlaying(false);update("angle",Math.min(config.maxAngle,config.angle+5));}}>+5°</button></div><button className={`simulator-play ${playing?"active":""}`} type="button" onClick={()=>setPlaying(p=>!p)}>{playing?"Pause":"Run"}</button></div></div></article>
        <section className="metric-grid"><article className={`metric-card ${pose&&pose.transmission<20?"metric-alert":""}`}><span>Transmission angle</span><strong>{pose?`${pose.transmission.toFixed(2)}°`:"—"}</strong><small>{pose?pose.transmission<20?"critical geometry":pose.transmission<35?"low":"usable":"unreachable"}</small></article><article className="metric-card"><span>Tool point T</span><strong>{pose?`${pose.T.x.toFixed(1)}, ${pose.T.y.toFixed(1)}`:"—"}</strong><small>x, y · mm</small></article><article className="metric-card metric-emphasis"><span>Required link torque</span><strong>{current.total?`${current.total.torque.toFixed(3)} N·m`:"—"}</strong><small>prescribed RPM/α at O₂</small></article><article className="metric-card"><span>Motor torque now</span><strong>{summary?.currentMotorTorque!==null&&summary?.currentMotorTorque!==undefined?`${summary.currentMotorTorque.toFixed(3)} N·m`:"—"}</strong><small>instantaneous vs peak rating</small></article></section>
        <section className="state-strip"><div><span>Output θ₄</span><strong>{pose?`${wrapDegrees(pose.theta4*DEG).toFixed(2)}°`:"—"}</strong></div><div><span>Velocity ratio ω₄/ω₂</span><strong>{kin?kin.omega4Ratio.toFixed(3):"—"}</strong></div><div><span>Tool Jacobian</span><strong>{kin?`${kin.toolDerivative.x.toFixed(1)}, ${kin.toolDerivative.y.toFixed(1)} mm/rad`:"—"}</strong></div></section>
      </section>
    </div>
    <section id="results" className="results-area"><div className="results-heading"><div><span className="panel-index">03</span><div><h2>Load analysis</h2><p>Adaptive planar inverse dynamics · convergence-aware peaks</p></div></div><button type="button" className="export-button" disabled={!adaptive} onClick={exportCsv}>Download analysis CSV</button></div>
      {!valid?<p className="analysis-note value-danger">Analysis paused: {Object.values(errors).join(" ")}</p>:null}{adaptive?.convergence.status!=="converged"?<p className="analysis-note value-danger">Adaptive solver status: {adaptive?.convergence.status}. Safety factors are withheld when a near-toggle region cannot be resolved.</p>:null}
      <section className="load-metric-grid"><article className={`load-metric primary-metric ${summary&&summary.peakUse>100?"load-warning":""}`}><span>Peak torque</span><strong>{summary?`${summary.peakTorque.toFixed(2)} N·m`:"—"}</strong><small>{peakMeta(adaptive?.peaks.peakTorque)}</small></article><article className="load-metric"><span>Peak joint reaction</span><strong>{summary?`${summary.peakJointForce.toFixed(0)} N`:"—"}</strong><small>{peakMeta(adaptive?.peaks.peakJointReaction)}</small></article><article className="load-metric"><span>Pin shear safety</span><strong>{safetyText(summary,summary?.shearSafety)}</strong><small>{summary?`${summary.shearStress.toFixed(1)} MPa nominal peak`:"—"}</small></article><article className="load-metric"><span>Link bearing safety</span><strong>{safetyText(summary,summary?.bearingSafety)}</strong><small>{summary?`${summary.bearingStress.toFixed(1)} MPa nominal peak`:"—"}</small></article></section>
      {adaptive?<section className="plot-grid"><Plot title="Input torque over motion window" unit="N·m at O₂" samples={samples} currentAngle={config.angle} value={(s)=>s.dynamics?.torque??null}/><Plot title="Transmission angle" unit="degrees · red zone below 20°" samples={samples} currentAngle={config.angle} value={(s)=>s.pose?.transmission??null} range={[0,90]} alertBelow={20}/></section>:null}
      <section className="load-detail-grid"><article className="detail-card actuator-card"><div className="detail-heading"><div><h3>Actuator & pin screen</h3><span>adaptive coarse-to-fine sampling</span></div><span className="angle-chip">{adaptive?.convergence.status??"analysis paused"}</span></div><div className="utilization-block"><div className="utilization-label"><span>Continuous / RMS torque</span><strong>{summary?.continuousUse!==null&&summary?.continuousUse!==undefined?`${summary.continuousUse.toFixed(0)}%`:"—"}</strong></div><div className="utilization-track"><i className={summary?.continuousUse!==null&&summary?.continuousUse!==undefined&&summary.continuousUse>100?"over":""} style={{width:`${Math.min(100,Math.max(0,summary?.continuousUse??0))}%`}}/></div><small>{summary?.rmsMotorTorque!==null&&summary?.rmsMotorTorque!==undefined?`${summary.rmsMotorTorque.toFixed(3)} N·m RMS / ${config.motorContinuous.toFixed(2)} N·m continuous`:"No valid RMS result"}</small></div><div className="utilization-block"><div className="utilization-label"><span>Peak torque</span><strong>{summary?`${summary.peakUse.toFixed(0)}%`:"—"}</strong></div><div className="utilization-track"><i className={summary&&summary.peakUse>100?"over":""} style={{width:`${Math.min(100,Math.max(0,summary?.peakUse??0))}%`}}/></div><small>{summary?`${summary.peakMotorTorque.toFixed(3)} N·m peak / ${config.motorPeak.toFixed(2)} N·m peak rating`:"—"}</small></div><div className="screening-grid"><div><span>Minimum μ</span><strong>{summary?`${summary.minTransmission.toFixed(2)}°`:"—"}</strong><small>{peakMeta(adaptive?.peaks.minTransmission)}</small></div><div><span>Peak motor speed</span><strong>{summary?`${summary.peakMotorSpeedRpm.toFixed(0)} rpm`:"—"}</strong></div><div><span>Peak mechanical power</span><strong>{summary?`${summary.peakMechanicalPowerW.toFixed(1)} W`:"—"}</strong></div><div><span>Adaptive samples</span><strong>{samples.length}</strong></div></div></article>
        <article className="detail-card"><div className="detail-heading"><div><h3>Current joint reactions</h3><span>signed components in global axes</span></div><span className="angle-chip">θ₂ {config.angle.toFixed(1)}°</span></div><div className="table-wrap"><table><thead><tr><th>Joint / body</th><th>Fx</th><th>Fy</th><th>Resultant</th></tr></thead><tbody>{reactions.length?reactions.map(([name,v])=><tr key={name}><td>{name}</td><td>{v.x.toFixed(1)} N</td><td>{v.y.toFixed(1)} N</td><td><strong>{magnitude(v).toFixed(1)} N</strong></td></tr>):<tr><td colSpan={4}>Current configuration is not dynamically solvable.</td></tr>}</tbody></table></div><div className="torque-breakdown"><div><span>Tool load</span><strong>{current.external?.torque.toFixed(3)??"—"} N·m</strong></div><div><span>Gravity</span><strong>{current.gravity?.torque.toFixed(3)??"—"} N·m</strong></div><div><span>Inertia</span><strong>{current.inertia?.torque.toFixed(3)??"—"} N·m</strong></div></div></article></section>
      <article className="assumption-strip"><strong>Model scope</strong><span>Rigid planar links</span><span>Ideal revolute joints</span><span>Constant configured RPM in dynamics</span><span>Configured constant input α</span><span>Preview endpoint reversal excluded from dynamics</span><span>RMS torque angle/time-weighted for constant speed</span><span>Nominal shear and projected bearing stress only</span></article>
    </section>
  </main>;
}
