export type Vec = { x: number; y: number };
export type MotionProfileType = "s-curve" | "sinusoidal";
export type MotionState = { time: number; phase: number; angle: number; theta: number; omega: number; alpha: number; jerk: number };
export type Pose = { O2: Vec; O4: Vec; A: Vec; B: Vec; T: Vec; theta2: number; theta3: number; theta4: number; transmission: number };
export type KinematicDerivatives = { omega3Ratio: number; omega4Ratio: number; toolDerivative: Vec };
export type KinematicState = { angle: number; pose: Pose; kinematics: KinematicDerivatives };
export type Dynamics = { torque: number; O2Reaction: Vec; AReaction: Vec; BReaction: Vec; O4Reaction: Vec; alpha3: number; alpha4: number };
export type DynamicsBreakdown = { total: Dynamics | null; external: Dynamics | null; gravity: Dynamics | null; inertia: Dynamics | null };
export type MotionPeak = { value: number | null; time: number | null; angle: number | null; resolution: number | null };
export type MotionSample = MotionState & { pose: Pose | null; kinematicState: KinematicState | null; dynamics: Dynamics | null; gravityTorque: number | null; inertiaTorque: number | null; jointReaction: number | null; linkPowerW: number | null };
export type MotionProfileInfo = { type: MotionProfileType; duration: number; halfDuration: number; peakVelocity: number; peakAcceleration: number; peakJerk: number; peakVelocityDegS: number; peakAccelerationDegS2: number; peakJerkDegS3: number; plan: unknown | null };
export type MotionAnalysis = { profile: MotionProfileInfo; reachability: { fullyReachable: boolean; degenerate: boolean; minDistance: number; maxDistance: number; lowerLimit: number; upperLimit: number }; status: string; samples: MotionSample[]; peaks: { peakTorque: MotionPeak; peakJointReaction: MotionPeak; peakLinkPower: MotionPeak; peakSpeed: MotionPeak } };
export type StaticSupport = { pose: Pose; kinematicState: KinematicState; effectiveMomentArmMm: number; signedVerticalArmMm: number; verticalSupportPerInputTorque: number; normalizedMechanicalAdvantage: number; singularVertical: boolean; supportForce: number; supportTorque: number | null; gravityTorque: number | null; holdingTorque: number | null };
export type StaticSupportSample = { angle: number; pose: Pose | null; kinematicState: KinematicState | null; support: StaticSupport | null };
export type StaticAnalysis = { status: string; stepDeg: number; samples: StaticSupportSample[]; reachability: MotionAnalysis["reachability"]; peaks: { minTransmission: MotionPeak; peakHoldingTorque: MotionPeak; peakGravityTorque: MotionPeak; maxMechanicalAdvantage: MotionPeak } };
export type AnalysisSummary = { motionValid: boolean; staticValid: boolean; peakTorque: number | null; peakJointForce: number | null; minTransmission: number | null; currentMotorTorque: number | null; peakMotorTorque: number | null; rmsMotorTorque: number | null; peakMotorSpeedRpm: number | null; peakMechanicalPowerW: number | null; peakStaticHoldTorque: number | null; peakStaticMotorTorque: number | null; currentStaticMotorTorque: number | null; shearStress: number | null; bearingStress: number | null; shearSafety: number | null; bearingSafety: number | null; continuousUse: number | null; peakUse: number | null; staticPeakUse: number | null };
export type MechanismClass = { ground: number; margin: number; grashof: boolean; type: string; inputRotates: boolean };
export const DEG: number;
export const RAD: number;
export function add(a: Vec, b: Vec): Vec;
export function analyzeMotion(config: object, options?: object): MotionAnalysis;
export function analyzeStaticSupport(config: object, options?: object): StaticAnalysis;
export function analysisToCsv(config: object, motionAnalysis: MotionAnalysis): string;
export function clamp(value: number, minimum: number, maximum: number): number;
export function dynamicsBreakdown(config: object, angleOrState?: number | KinematicState, motion?: Partial<MotionState>, externalForce?: Vec): DynamicsBreakdown;
export function inverseDynamics(config: object, angleOrState?: number | KinematicState, motion?: Partial<MotionState>, externalForce?: Vec): Dynamics | null;
export function kinematics(config: object, angleDegrees?: number, pose?: Pose | null): KinematicDerivatives | null;
export function kinematicStateAtAngle(config: object, angleDegrees?: number): KinematicState | null;
export function magnitude(vector: Vec): number;
export function mechanismClass(config: object): MechanismClass;
export function motionProfileInfo(config: object): MotionProfileInfo;
export function motionStateAtTime(config: object, time: number): MotionState;
export function motionWindowReachability(config: object): MotionAnalysis["reachability"];
export function mul(a: Vec, scalar: number): Vec;
export function sampleAngleRange(minimum: number, maximum: number, step: number): number[];
export function sampleMotionProfile(config: object, options?: object): MotionState[];
export function solvePose(config: object, angleDegrees?: number): Pose | null;
export function staticInputTorqueFromJacobian(config: object, angleDegrees: number, force?: Vec): number | null;
export function staticSupportAtAngle(config: object, angleDegrees: number, supportForce?: number): StaticSupport | null;
export function staticSupportFromKinematicState(config: object, state: KinematicState, supportForce?: number): StaticSupport | null;
export function summarizeAnalysis(config: object, motion: MotionAnalysis, staticAnalysis: StaticAnalysis, currentDynamics?: DynamicsBreakdown | null, currentSupport?: StaticSupport | null): AnalysisSummary;
export function timeAtAngle(config: object, angleDegrees: number): number;
export function wrapDegrees(value: number): number;
